beach = Beach.create(name: 'Manly')
beach = Beach.create(name: 'Bondi')
beach = Beach.create(name: 'Dee Why')
beach = Beach.create(name: 'Curl Curl')
beach = Beach.create(name: 'Freshwater')
beach = Beach.create(name: 'Palm')
beach = Beach.create(name: 'Coogee')
beach = Beach.create(name: 'Tamarama')
beach = Beach.create(name: 'Dead Mans')
beach = Beach.create(name: 'Collaroy')
beach = Beach.create(name: 'Turimetta')
beach = Beach.create(name: 'Warriewood')
beach = Beach.create(name: 'Mona Vale')
beach = Beach.create(name: 'Newport')
beach = Beach.create(name: 'Avalon')
beach = Beach.create(name: 'Whale')


session = Session.create!(beach_id: 1, date: Date.today(), board: 'fish', description: 'Great!')
session = Session.create!(beach_id: 2, date: Date.today(), board: 'mini mal', description: 'Great!!!')